#!/bin/bash
# Variables you might want to change.
editor='scribe'
location="$HOME/.config/keepwritings/history"
originaldir="$PWD"

# Check for arguments
if [[ $# -gt 1 ]]; then
	echo "Keepwritings doesn't take more than one argument."
	exit.
fi

# Set date.
date="$(date +"%a-%Y-%m-%d-%R")"
filename="$date"

# cd to the directory where the magic happens.
cd $location

# Make a writing, and keep it.
$editor "$filename"
# xclip "$filename" # Optional feature. Uncomment this if you want to automatically load writings into the clipboard after saving them.
# sed -i "s/^/$date: /" "$filename" # Embeds date inside the file itself. Don't use; lame.
echo "" >> "$filename"
if [[ $# -eq 1 ]]; then
	ln -s -T "$HOME/.config/keepwritings/history/$filename/" "$originaldir/$1"
fi

# Optionally, you can have the text pasted automatically after you quit the editor. Discouraged, as it can be annoying if you don't focus the appropriate text field before launching keepwritings. To enable, uncomment the following line.
#xte "str $(xclip -o)"
