#!/bin/bash

# Variables you might want to change.
editor='gedit'

# Set date.
date=$(date +"%a %Y-%m-%d %R")
filename=$date

# Installation. Only relevant when run for the first time.
if [[ ! -d ~/.config/keepwritings ]]
	then mkdir -p ~/.config/keepwritings/history
fi

# Make a writing, and keep it.
cd ~/.config/keepwritings
rm current.txt
$editor current.txt
xclip current.txt
cat current.txt >> "history/$filename.txt"
sed -i "s/^/$date: /" "history/$filename.txt"

