#!/bin/bash

cd "$HOME/.config/keepwritings/history/" # Go to where the magic happens.
dirs="$(ls -d */ | sed 's/\///')"

for dir in $dirs
do
	withdate="$(cat "$dir/$dir" | xargs -I {} echo "$dir {}")"$'\n'
	all="$all""$withdate"
done


# Recall.
date="$(echo "$all" | dmenu -i -b -l 30 | cut -c -20)"
if [[ ! $date -eq 0 ]]; then
	scribe "$date"
fi
# xclip "$date" # Uncomment this if you want to automatically load the writing into memory after saving it.
